config/routes.rb
Rails.application.routes.draw do

	get 'todos', to: 'todos#index'
	get 'todos/new'
	get 'todos/list'
	post 'todos', to: 'todos#create'
	get 'todos/:id', to: 'todos#show', as: 'todo'
	get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
	patch 'todos/:id', to: 'todos#update'
	delete 'todos/:id', to: 'todos#destroy'
	get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end

	def complete
		@todo = Todo.find(params[:id])
		@todo.completed = 1
		@todo.save
		redirect_to todos_path
	end

	def list
		@todos = Todo.all
	end


	private

	def todo_params
		params.require(:todo).permit(:description, :completed)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
	<div class="col-12">
		<%= link_to "Index", todos_path, :class => "navbar-brand" %>
		<%= link_to "Lista", todos_list_path, :class => "navbar-brand" %>
		<%= link_to "Crear ToDo", todos_new_path, :class => "navbar-brand" %>
	
	</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script   src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>

	<%= f.label :description %>:<br>
	<%= f.text_area :description, size: "50x5" %><br>

	<%= f.label :completed %>:
	<%= f.check_box :completed %><br>

	<%= f.submit "Enviar" %>

<% end %>

app/views/todos/edit.html.erb
<div class="container">
<h1>Editar Todo</h1>

<%= render 'form' %>




</div>

app/views/todos/index.html.erb
<br><br><br>
<div class="container">
<h1>ToDo Index</h1><br>

<%= link_to "Ingresar un nuevo ToDo", todos_new_path, :class => "h4 btn btn-info" %><br><br>


<% @todos.each do |todo| %>
	<div class="card">

		<div class="col-12">Descripción: <%= todo.description%> <%= link_to "Ver ToDo", todo, :class => "btn btn-light ml-3" %>
			<%= link_to "Editar ToDo", edit_todo_path(todo), :class => "btn btn-info ml-3" %>
			<%= link_to "Borrar ToDo", todo, method: :delete, :class => "btn btn-dark ml-3" %>
			<%= link_to "Marcar Completed", complete_todo_path(todo), :class => "btn btn-dark ml-3" %>
		</div>
		<div class="col-8">Completed: <%= todo.completed %></div>
	
	</div>
<% end %>
</div>

app/views/todos/list.html.erb
<br><br><br>
<h1>ToDo List</h1><br>


<div class="row">
	<div class="col-md-6">

		<h2>ToDo's Incompletos</h2>
	
		<% @todos.each do |todo| %>

			<% if todo.completed == false %>
				
					<div class="card"><%= todo.description%> </div>
				
			<% end %>
		<% end %>

	</div>

	<div class="col-md-6">
	<h2>ToDo's Completados</h2>
	
		<% @todos.each do |todo| %>

			<% if todo.completed == true %>
				
					<div class="card"><%= todo.description%> </div>
				
			<% end %>
			
		<% end %>

	</div>

</div>

app/views/todos/new.html.erb
<br><br><br>
<div class="container">
<h2>Nuevo Todo</h2>

<%= render 'form' %>




</div>

app/views/todos/show.html.erb
<div class="container">
<h1>Show un ToDo</h1><br>


	<div class="card">

		<div class="col-6">Descripción: <%= @todo.description %></div>
		<div class="col-6">Completed: <%= @todo.completed %></div>
	</div>
	
	
</div>